---
# sdev_home_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}"
sdev_username: root # TODO: change to studio-user when available on Packer-Studio
sdev_home_dir: /tmp
sdev_profile_file: .zprofile
sdev_poetry_dir: /tmp/poetry
sdev_repoman_link_src: /tmp/stage/repoman
sdev_ssh_config_link_src: /tmp/stage/sshconfig
sdev_ssh_config_file: config
sdev_ssh_configd_link_src: /tmp/stage/sshconfigd
sdev_ssh_configd_file: configd
sdev_ssh_private_key_link_src: /tmp/stage/id_ed25519
sdev_ssh_public_key_link_src: /tmp/stage/id_ed25519.pub
sdev_sshkey_name: id_ed25519
sdev_git_aliases_file: aliases-git.zsh
sdev_gitconfig_link_src: /tmp/stage/.gitconfig
sdev_gitconfig_file: .gitconfig
sdev_gpgagent_conf_file: gpg-agent.conf
sdev_npm_packages:
  - repoman
sdev_workspaces:
  - control
sdev_vscode_workspaces:
  - control
sdev_colima_networks:
  - studio
sdev_docker_images:
  - { id: 'studio', image: 'cliffano/studio', env_file: '/tmp/stage/.env', home_dir: 'root', entrypoint: '/bin/bash' }
sdev_ghostty_config_dir: /tmp/stage/ghostty
sdev_ghostty_profiles:
  - id: control
    title: Control
    working_directory: /tmp/dev/workspace-control
  - id: studio
    title: Studio
    working_directory: /tmp/dev/workspace-studio
