---
# sdev_home_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}"
sdev_home_dir: /tmp
sdev_profile_file: .zprofile
sdev_git_aliases_file: aliases-git.zsh
sdev_gitconfig_link_src: /tmp/stage/test-fixtures/.gitconfig
sdev_gitconfig_file: .gitconfig
sdev_gpgagent_conf_file: gpg-agent.conf