---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: default
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
    hostname: localhost
    connection_options:
      ansible_connection: local
provisioner:
  name: ansible
verifier:
  name: testinfra
