set-option -g set-clipboard on
set -g default-terminal "tmux-256color"
set -g pane-border-status top
set -g pane-border-format " #{pane_index}: #{pane_title} "
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=green
